Repository JandiGoorm/jandi_band_frontend, pull requests merged in 2025-06, with the labels that each got.

#37 [Feature/toast UI] 토스트 컴포넌트 로직 및 UI 수정, 데이터 페칭 수정
  src/apis/club.ts
  src/apis/team.ts
  src/apis/utils.ts
  src/components/toast/GlobalToast.module.css
  src/components/toast/GlobalToast.tsx
  src/config/queryClient.ts
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/detail/clubInfo/ModifyClubModal.tsx
  src/pages/invite/Invite.tsx
  src/pages/team/detail/TeamDetail.tsx
  src/pages/team/detail/teamMembers/TeamMembers.module.css
  src/pages/team/detail/teamMembers/TeamMembers.tsx
Labels: bug, Design

#43 [Feature/api promotion]홍보물 detail페이지 api 연결
  src/components/pagination/Pagination.tsx
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/DetailContent.module.css
  src/pages/promotions/detail/DetailContent.tsx
  src/utils/dateStatus.ts
Labels: Design, Feature, Chore

#44 [Feature/api-calendar] 캘린더 api 연결
  src/apis/calendar.ts
  src/apis/secureRoutes.ts
  src/constants/endpoints.ts
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubCalendar/calendar/Cells.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/data.ts
  src/stores/clubStore.ts
  src/types/calendar.ts
Labels: Design, Feature

#45 [build:react-version] 버전 변경
  package-lock.json
  package.json
Labels: Chore

#49 [Feature/api-calendar] 캘린더 일정 추가 및 모달에서 삭제 기능 추가
  src/apis/calendar.ts
  src/apis/secureRoutes.ts
  src/constants/endpoints.ts
  src/pages/club/detail/clubCalendar/ScheduleModal.tsx
  src/pages/club/detail/clubCalendar/calendar/Calendar.tsx
  src/pages/club/detail/clubCalendar/calendar/Cells.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/ModalItem.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.tsx
  src/pages/club/detail/clubInfo/ClubInfo.module.css
  src/stores/currentStore.ts
  src/types/calendar.ts
Labels: Design, Feature

#52 [Feature/promotion map] 카카오 맵 관련 api 적용 및 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/apis/promotion.ts
  src/apis/secureRoutes.ts
  src/components/modal/mapModal/MapModal.module.css
  src/components/modal/mapModal/MapModal.tsx
  src/constants/endpoints.ts
  src/hooks/useKakao.ts
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/DetailContent.module.css
  src/pages/promotions/detail/DetailContent.tsx
  src/pages/promotions/detail/LocationModal.module.css
  src/pages/promotions/detail/LocationModal.tsx
  src/pages/promotions/map/PromoComponent.tsx
  src/pages/promotions/map/PromotionComponent.module.css
  src/pages/promotions/map/PromotionMap.module.css
  src/pages/promotions/map/PromotionMap.tsx
  src/pages/promotions/post/CreatePost.tsx
  src/pages/promotions/update/UpdatePromotion.tsx
  src/types/kakao.ts
  src/types/promotion.ts
  src/utils/dateStatus.ts
  src/variables.css
Labels: Design, Feature, Chore

#53 [Feature/api promotion]게시물 좋아요 설정 적용
  src/apis/hooks.ts
  src/apis/promotion.ts
  src/apis/secureRoutes.ts
  src/constants/endpoints.ts
  src/pages/promotions/detail/DetailContent.tsx
  src/types/promotion.ts
Labels: Feature, Chore

#55 [Feature/members] 사용자 권한 관련 api 적용 및 페이지 접근 관리, 기타 수정
  package-lock.json
  package.json
  public/basic_club.png
  src/App.tsx
  src/apis/club.ts
  src/apis/secureRoutes.ts
  src/apis/team.ts
  src/components/button/Button.module.css
  src/components/cards/TeamCard.tsx
  src/components/dropdown/Dropdown.module.css
  src/components/dropdown/Dropdown.tsx
  src/components/input/Input.module.css
  src/components/modal/Modal.tsx
  src/components/modal/inviteModal/InviteModal.tsx
  src/components/modal/leaveModal/LeaveModal.module.css
  src/components/modal/leaveModal/LeaveModal.tsx
  src/components/slide/MainSlide.tsx
  src/components/tooltip/Tooltip.module.css
  src/components/tooltip/Tooltip.tsx
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.module.css
  src/layouts/defaultLayout/Header.tsx
  src/pages/auth/signIn/Callback.tsx
  src/pages/auth/signUp/SignUpForm.tsx
  src/pages/club/detail/ClubDetail.module.css
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubCalendar/ScheduleModal.tsx
  src/pages/club/detail/clubInfo/ClubInfo.module.css
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/detail/clubInfo/EditMemberButton.tsx
  src/pages/club/detail/clubInfo/EditMemberModal.module.css
  src/pages/club/detail/clubInfo/EditMemberModal.tsx
  src/pages/club/detail/clubInfo/ModifyClubModal.tsx
  src/pages/club/detail/clubSlide/TeamSlide.module.css
  src/pages/club/detail/clubSlide/VoteSlide.module.css
  src/pages/club/detail/clubSlide/modalContent/TeamModal.tsx
  src/pages/club/detail/clubSlide/modalContent/VoteModal.tsx
  src/pages/club/more/ClubList.module.css
  src/pages/club/more/ClubList.tsx
  src/pages/club/more/MyClubList.module.css
  src/pages/club/more/MyClubList.tsx
  src/pages/home/BandSlide.module.css
  src/pages/home/BandSlide.tsx
  src/pages/home/CreateClubModal.module.css
  src/pages/home/CreateClubModal.tsx
  src/pages/home/MyBandSlide.module.css
  src/pages/home/MyBandSlide.tsx
  src/pages/home/PromotionSlide.module.css
  src/pages/home/PromotionSlide.tsx
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/map/PromotionMap.tsx
  src/pages/team/detail/TeamDetail.tsx
  src/pages/team/detail/scheduleBoard/AddPractice.tsx
  src/pages/vote/select/Recommend.tsx
  src/routes/PrivateRoute.tsx
  src/routes/Routes.tsx
  src/types/auth.ts
  src/variables.css
Labels: bug, Design, Feature, Chore

#57 [Feature/vote filter] 투표 결과 필터링 및 모바일 가로 스크롤, 순위 텍스트 추가
  src/pages/vote/graph/BarChart.module.css
  src/pages/vote/graph/BarChart.tsx
  src/pages/vote/result/FilterSelect.module.css
  src/pages/vote/result/FilterSelect.tsx
  src/pages/vote/result/VoteResult.module.css
  src/pages/vote/result/VoteResult.tsx
Labels: Design, Feature

#58 [Design/refactor] 시간표 UI, 탈퇴 UI 수정
  src/components/scheduler/TimeBoard.module.css
  src/components/scheduler/TimeLine.module.css
  src/components/scheduler/TimeScheduler.module.css
  src/pages/club/detail/ClubDetail.module.css
  src/pages/club/detail/ClubDetail.tsx
  src/pages/team/detail/CreateTimeTable.module.css
  src/pages/team/detail/CreateTimeTable.tsx
  src/pages/team/detail/TeamDetail.module.css
  src/pages/team/detail/TeamDetail.tsx
Labels: Design

#59 [Design/refactor] 1차 UI 리팩토링
  src/components/slide/MainSlide.module.css
  src/pages/home/BandSlide.module.css
  src/pages/home/BandSlide.tsx
  src/pages/home/Banner.module.css
  src/pages/home/Home.module.css
  src/pages/home/MyBandSlide.module.css
  src/pages/home/MyBandSlide.tsx
  src/pages/home/PromotionSlide.module.css
  src/pages/home/PromotionSlide.tsx
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/Comment.module.css
  src/pages/promotions/detail/Comment.tsx
  src/pages/promotions/detail/DetailContent.module.css
  src/pages/promotions/detail/DetailContent.tsx
Labels: Design

#60 [Design/main] 로그인 랜딩 페이지 제작 (소개 부분)
  src/components/modal/inviteModal/InviteModal.tsx
  src/pages/auth/signIn/InfoSection.module.css
  src/pages/auth/signIn/InfoSection.tsx
  src/pages/auth/signIn/SignIn.module.css
  src/pages/auth/signIn/SignIn.tsx
  src/pages/club/detail/clubInfo/InviteModal.tsx
Labels: Design, Feature

#61 [Feature/club photo]동아리 사진 기능 추가
  src/apis/photo.ts
  src/apis/secureRoutes.ts
  src/components/cards/PhotoCard.module.css
  src/components/cards/PhotoCard.tsx
  src/components/dropdown/Dropdown.module.css
  src/components/dropdown/Dropdown.tsx
  src/components/modal/Modal.module.css
  src/components/modal/photoModal/PhotoModal.module.css
  src/components/modal/photoModal/PhotoModal.tsx
  src/components/select/UniversitySelect.module.css
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.tsx
  src/pages/auth/signUp/PositionSelect.module.css
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/detail/clubInfo/ModifyProfileModal.tsx
  src/pages/club/detail/clubSlide/PhotoSlide.module.css
  src/pages/club/detail/clubSlide/PhotoSlide.tsx
  src/pages/club/detail/clubSlide/modalContent/PhotoModal.tsx
  src/pages/club/more/PhotoList.module.css
  src/pages/club/more/PhotoList.tsx
  src/pages/team/detail/TeamDetail.tsx
  src/routes/Routes.tsx
  src/types/photo.ts
  src/variables.css
Labels: Design, Feature, Chore

#63 [Feature/refactor mg] 오류사항 수정 및 검색 기능
  src/apis/promotion.ts
  src/apis/secureRoutes.ts
  src/apis/team.ts
  src/components/cards/TimeTableCards.module.css
  src/components/cards/TimeTableCards.tsx
  src/components/modal/mapModal/MapModal.tsx
  src/constants/endpoints.ts
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/more/ClubList.module.css
  src/pages/club/more/ClubList.tsx
  src/pages/club/more/MyClubList.module.css
  src/pages/club/more/MyClubList.tsx
  src/pages/home/BandSlide.tsx
  src/pages/home/MyBandSlide.module.css
  src/pages/home/MyBandSlide.tsx
  src/pages/mypage/MyPage.module.css
  src/pages/mypage/MyPage.tsx
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/PromotionDetail.module.css
  src/pages/promotions/detail/PromotionDetail.tsx
  src/pages/promotions/map/PromotionMap.module.css
  src/pages/promotions/map/PromotionMap.tsx
  src/pages/promotions/post/CreatePost.tsx
  src/pages/promotions/update/UpdatePromotion.tsx
  src/pages/team/detail/TeamDetail.tsx
  src/pages/timeSchedule/detail/TimeScheduleDetail.module.css
  src/pages/timeSchedule/detail/TimeScheduleDetail.tsx
  src/pages/timeSchedule/post/TimeSchedule.module.css
  src/pages/timeSchedule/post/TimeSchedule.tsx
Labels: bug, Feature, Chore

#64 feat: Inter 폰트 설정
  src/global.css
  src/main.tsx
Labels: Design

#66 [Feature/message-vote] 곡 투표 카톡 공유 추가
  src/pages/invite/Invite.tsx
  src/pages/vote/select/Vote.tsx
Labels: Feature

#68 [Fix/refactor] 1차 리팩토링 - 연습 일정, 마이페이지, 그래프, 페이지네이션, 공연 홍보 게시판
  src/apis/mypage.ts
  src/components/button/Button.module.css
  src/components/button/Button.tsx
  src/components/cards/TeamCard.module.css
  src/components/cards/VoteCard.module.css
  src/components/pagination/Pagination.module.css
  src/components/pagination/Pagination.tsx
  src/pages/club/detail/clubCalendar/calendar/Calendar.module.css
  src/pages/club/detail/clubCalendar/calendar/Header.module.css
  src/pages/club/detail/clubInfo/ClubInfo.module.css
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/ProfilEdit.tsx
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/Comment.module.css
  src/pages/promotions/detail/Comment.tsx
  src/pages/promotions/detail/DetailContent.module.css
  src/pages/promotions/post/CreatePost.module.css
  src/pages/team/detail/scheduleBoard/AddPractice.tsx
  src/pages/vote/graph/BarChart.module.css
  src/pages/vote/graph/BarChart.tsx
  src/pages/vote/result/VoteResult.tsx
  src/pages/vote/select/Recommend.tsx
  src/pages/vote/select/Vote.tsx
  src/pages/vote/select/VoteSongCard.module.css
  src/utils/dateStatus.ts
  src/variables.css
Labels: bug, Design, Feature

#70 [Feature/message vote] 곡 투표 카카오톡 연결 (dev로 재PR)
  src/pages/invite/Invite.tsx
  src/pages/vote/select/Vote.tsx
Labels: Feature

#71 [Fix/refactor] 2차 리팩토링 - 캘린더, 동아리 일정 모달, 그 외 팀 모달창 수정 (+웹폰트 변경)
  src/components/modal/inviteModal/InviteModal.module.css
  src/global.css
  src/pages/club/detail/clubCalendar/ScheduleModal.module.css
  src/pages/club/detail/clubCalendar/calendar/Cells.module.css
  src/pages/club/detail/clubCalendar/calendar/Cells.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/ModalItem.module.css
  src/pages/club/detail/clubCalendar/calendarLabel/ModalItem.tsx
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.module.css
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.tsx
  src/pages/club/detail/clubSlide/modalContent/VoteModal.module.css
  src/pages/mypage/MyPage.module.css
  src/pages/mypage/ProfilEdit.tsx
Labels: bug, Design

#72 fix: 이미 가입한 동아리일 시 무한로딩 수정
  src/pages/invite/Invite.tsx
Labels: bug

#73 [Feature/refactor-mg]지도 수정 및 기타 css 수정
  src/App.tsx
  src/apis/promotion.ts
  src/apis/secureRoutes.ts
  src/components/cards/TeamCard.module.css
  src/components/cards/TeamCard.tsx
  src/components/cards/VoteCard.module.css
  src/components/modal/mapModal/MapModal.module.css
  src/components/modal/mapModal/MapModal.tsx
  src/components/modal/reportModal/ReportModal.module.css
  src/components/modal/reportModal/ReportModal.tsx
  src/components/slide/Slide.tsx
  src/layouts/defaultLayout/Header.module.css
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.module.css
  src/pages/club/detail/clubCalendar/calendarLabel/ScheduleModal.tsx
  src/pages/club/detail/clubSlide/PhotoSlide.module.css
  src/pages/club/detail/clubSlide/PhotoSlide.tsx
  src/pages/club/detail/clubSlide/VoteSlide.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/detail/CommentItem.tsx
  src/pages/promotions/detail/DetailContent.tsx
  src/pages/promotions/detail/LocationModal.module.css
  src/pages/promotions/map/PromotionComponent.module.css
  src/pages/promotions/map/PromotionMap.module.css
  src/routes/ScrollToTop.tsx
  src/types/promotion.ts
Labels: bug, Design, Feature

#80 [Fix/refactor] 시간표 불러오기 모달 수정 및 에타 연동
  src/components/cards/TimeTableCards.module.css
  src/pages/footer/PrivacyPolicy.tsx
  src/pages/team/detail/CreateTimeTable.module.css
  src/pages/team/detail/CreateTimeTable.tsx
  src/pages/team/detail/modals/LoadSchedules.module.css
  src/pages/team/detail/modals/LoadSchedules.tsx
  src/pages/timeSchedule/post/TimeSchedule.module.css
  src/pages/vote/graph/BarChart.module.css
Labels: bug, Design, Feature

#84 [Fix/refactor] 모바일 시간표 드래그 기능 추가
  src/components/scheduler/SelectableArea.tsx
  src/components/scheduler/TimeBoard.module.css
  src/components/scheduler/TimeLine.module.css
  src/global.css
Labels: Fix, Feature, Refactor

#89 [Feature/refactor mg] 회원탈퇴 구현, 트러블 슈팅 대응, API 연결 예외처리
  src/App.tsx
  src/apis/auth.ts
  src/apis/secureRoutes.ts
  src/apis/utils.ts
  src/components/dropdown/Dropdown.tsx
  src/components/modal/Modal.module.css
  src/components/tooltip/Tooltip.tsx
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.module.css
  src/layouts/defaultLayout/Header.tsx
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/mypage/MyPage.module.css
  src/pages/mypage/MyPage.tsx
  src/pages/notFound/NotFound.module.css
  src/pages/notFound/NotFound.tsx
  src/pages/promotions/PromotionMain.tsx
  src/pages/team/detail/CreateTimeTable.module.css
  src/pages/team/detail/TeamDetail.module.css
  src/pages/team/detail/TeamDetail.tsx
  src/pages/team/detail/modals/LoadSchedules.module.css
  src/pages/vote/select/Vote.module.css
  src/pages/vote/select/Vote.tsx
  src/stores/toastStore.ts
  src/utils/ErrorRedirectHandler.ts
  src/utils/dateStatus.ts
Labels: Design, Feature, Chore, Bug
