Repository JandiGoorm/jandi_band_frontend, pull requests merged in 2025-05, with the labels that each got.

#3 [Design/song vote] 곡 선정 화면 디자인
  index.html
  public/favicon.png
  public/favicon.svg
  public/logo_anti.png
  src/App.tsx
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.module.css
  src/layouts/defaultLayout/Header.tsx
  src/pages/vote/Vote.tsx
  src/pages/vote/VoteSongCard.tsx
  src/pages/vote/embed.ts
  src/pages/vote/result/VoteResult.tsx
  src/pages/vote/style/Vote.module.css
  src/pages/vote/style/VoteSongCard.module.css
  src/pages/vote/style/kakao.svg
  src/pages/vote/style/profile.svg
Labels: Design

#4 Design: 공연홍보 메인, 디테일페이지 제작
  public/promotion1.png
  public/promotion2.png
  public/promotion3.png
  src/App.tsx
  src/components/button/Button.module.css
  src/components/button/Button.stories.ts
  src/components/button/Button.test.tsx
  src/components/button/Button.tsx
  src/components/input/Input.module.css
  src/components/input/Input.tsx
  src/constants/endpoints.ts
  src/pages/auth/signIn/SignIn.module.css
  src/pages/auth/signUp/SignUp.module.css
  src/pages/auth/signUp/SignUpForm.module.css
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/constants.ts
  src/pages/promotions/detail/Comment.module.css
  src/pages/promotions/detail/Comment.tsx
  src/pages/promotions/detail/DetailContent.module.css
  src/pages/promotions/detail/DetailContent.tsx
  src/pages/promotions/detail/PromotionDetail.module.css
  src/pages/promotions/detail/PromotionDetail.tsx
  src/utils/buildPath.ts
  src/variables.css
Labels: Design

#8 [Design/song vote] 그래프 라이브러리 추가
  package-lock.json
  package.json
  src/App.tsx
  src/constants/endpoints.ts
  src/pages/vote/graph/BarChart.module.css
  src/pages/vote/graph/BarChart.tsx
  src/pages/vote/graph/voteData.ts
  src/pages/vote/result/VoteResult.module.css
  src/pages/vote/result/VoteResult.tsx
  src/pages/vote/select/Vote.module.css
  src/pages/vote/select/Vote.tsx
  src/pages/vote/select/VoteSongCard.module.css
  src/pages/vote/select/VoteSongCard.tsx
  src/pages/vote/style/arrowback.svg
Labels: Design, Feature

#9 [Design/club] 동아리메인페이지 제작
  package-lock.json
  package.json
  public/banner.png
  src/App.tsx
  src/components/input/Input.module.css
  src/components/modal/Modal.module.css
  src/components/modal/Modal.tsx
  src/components/slide/Slide.module.css
  src/components/slide/Slide.tsx
  src/constants/endpoints.ts
  src/hooks/uesCalendarNavigation.ts
  src/pages/club/main/Club.module.css
  src/pages/club/main/Club.tsx
  src/pages/club/main/clubCalendar/ClubCalendar.module.css
  src/pages/club/main/clubCalendar/ClubCalendar.tsx
  src/pages/club/main/clubCalendar/ScheduleModal.module.css
  src/pages/club/main/clubCalendar/ScheduleModal.tsx
  src/pages/club/main/clubCalendar/calendar/Calendar.module.css
  src/pages/club/main/clubCalendar/calendar/Calendar.tsx
  src/pages/club/main/clubCalendar/calendar/Cells.module.css
  src/pages/club/main/clubCalendar/calendar/Cells.tsx
  src/pages/club/main/clubCalendar/calendar/Days.module.css
  src/pages/club/main/clubCalendar/calendar/Days.tsx
  src/pages/club/main/clubCalendar/calendar/Header.module.css
  src/pages/club/main/clubCalendar/calendar/Header.tsx
  src/pages/club/main/clubInfo/ClubInfo.module.css
  src/pages/club/main/clubInfo/ClubInfo.tsx
  src/pages/club/main/clubSlide/PhotoSlide.module.css
  src/pages/club/main/clubSlide/PhotoSlide.tsx
  src/pages/club/main/clubSlide/TeamSlide.module.css
  src/pages/club/main/clubSlide/TeamSlide.tsx
  src/pages/club/main/clubSlide/VoteSlide.module.css
  src/pages/club/main/clubSlide/VoteSlide.tsx
  src/pages/club/main/clubSlide/modalContent/MemberSelect.module.css
  src/pages/club/main/clubSlide/modalContent/MemberSelect.tsx
  src/pages/club/main/clubSlide/modalContent/PhotoModal.module.css
  src/pages/club/main/clubSlide/modalContent/PhotoModal.tsx
  src/pages/club/main/clubSlide/modalContent/TeamModal.module.css
  src/pages/club/main/clubSlide/modalContent/TeamModal.tsx
  src/pages/club/main/clubSlide/modalContent/UniversitySelect.module.css
  src/pages/club/main/clubSlide/modalContent/UniversitySelect.tsx
  src/pages/club/main/clubSlide/modalContent/VoteModal.module.css
  src/pages/club/main/clubSlide/modalContent/VoteModal.tsx
  src/pages/club/main/clubSlide/modalContent/constants.ts
  src/variables.css
Labels: Design

#10 [Design/promo post] 공연 홍보 글 작성 페이지
  src/App.tsx
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.module.css
  src/pages/promotions/PromotionMain.module.css
  src/pages/promotions/PromotionMain.tsx
  src/pages/promotions/post/CreatePost.module.css
  src/pages/promotions/post/CreatePost.tsx
Labels: bug, Design, Feature

#14 [Feature/api auth] 로그인 관련 API 연동
  src/App.tsx
  src/apis/auth.ts
  src/apis/hooks.ts
  src/apis/secureRoutes.ts
  src/apis/types.ts
  src/apis/utils.ts
  src/components/loading/Loading.module.css
  src/components/loading/Loading.tsx
  src/constants/endpoints.ts
  src/layouts/defaultLayout/Header.tsx
  src/pages/auth/signIn/Callback.tsx
  src/pages/auth/signUp/SignUpForm.tsx
  src/stores/authStore.ts
  src/types/auth.ts
  src/types/common.ts
  src/variables.css
Labels: Feature

#16 [Design/mypage] 마이페이지 UI
  public/camera.svg
  public/modal_cancle.svg
  public/musical_note1.svg
  public/musical_notes2.svg
  src/App.tsx
  src/components/modal/Modal.module.css
  src/components/modal/Modal.tsx
  src/components/slide/Slide.module.css
  src/components/slide/Slide.tsx
  src/constants/endpoints.ts
  src/pages/mypage/MyPage.module.css
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/ProfilEdit.tsx
  src/pages/mypage/ProfileEdit.module.css
  src/pages/promotions/post/CreatePost.tsx
Labels: Design, Feature

#15 [Feature/api auth] 사용자 버그 수정 및 Toast추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/toast/GlobalToast.module.css
  src/components/toast/GlobalToast.tsx
  src/layouts/defaultLayout/DefaultLayout.tsx
  src/pages/auth/signIn/Callback.tsx
  src/stores/toastStore.ts
  src/utils/random.ts
Labels: bug, Feature, Chore

#21 [Feature/api club] api 훅 타입수정 및 club관련 api연동
  src/App.tsx
  src/apis/auth.ts
  src/apis/club.ts
  src/apis/hooks.ts
  src/apis/poll.ts
  src/apis/secureRoutes.ts
  src/apis/univ.ts
  src/apis/utils.ts
  src/components/field/Field.module.css
  src/components/field/Field.tsx
  src/components/select/UniversitySelect.module.css
  src/components/select/UniversitySelect.tsx
  src/components/toast/GlobalToast.module.css
  src/components/toast/GlobalToast.tsx
  src/config/queryClient.ts
  src/constants/endpoints.ts
  src/layouts/defaultLayout/CreateClubModal.module.css
  src/layouts/defaultLayout/CreateClubModal.tsx
  src/layouts/defaultLayout/Header.module.css
  src/layouts/defaultLayout/Header.tsx
  src/pages/auth/signUp/SignUpForm.tsx
  src/pages/club/detail/ClubDetail.module.css
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubCalendar/ClubCalendar.module.css
  src/pages/club/detail/clubCalendar/ClubCalendar.tsx
  src/pages/club/detail/clubCalendar/ScheduleModal.module.css
  src/pages/club/detail/clubCalendar/ScheduleModal.tsx
  src/pages/club/detail/clubCalendar/calendar/Calendar.module.css
  src/pages/club/detail/clubCalendar/calendar/Calendar.tsx
  src/pages/club/detail/clubCalendar/calendar/Cells.module.css
  src/pages/club/detail/clubCalendar/calendar/Cells.tsx
  src/pages/club/detail/clubCalendar/calendar/Days.module.css
  src/pages/club/detail/clubCalendar/calendar/Days.tsx
  src/pages/club/detail/clubCalendar/calendar/Header.module.css
  src/pages/club/detail/clubCalendar/calendar/Header.tsx
  src/pages/club/detail/clubInfo/ClubInfo.module.css
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/detail/clubSlide/PhotoSlide.module.css
  src/pages/club/detail/clubSlide/PhotoSlide.tsx
  src/pages/club/detail/clubSlide/TeamSlide.module.css
  src/pages/club/detail/clubSlide/TeamSlide.tsx
  src/pages/club/detail/clubSlide/VoteSlide.module.css
  src/pages/club/detail/clubSlide/VoteSlide.tsx
  src/pages/club/detail/clubSlide/modalContent/MemberSelect.module.css
  src/pages/club/detail/clubSlide/modalContent/MemberSelect.tsx
  src/pages/club/detail/clubSlide/modalContent/PhotoModal.module.css
  src/pages/club/detail/clubSlide/modalContent/PhotoModal.tsx
  src/pages/club/detail/clubSlide/modalContent/TeamModal.module.css
  src/pages/club/detail/clubSlide/modalContent/TeamModal.tsx
  src/pages/club/detail/clubSlide/modalContent/UniversitySelect.module.css
  src/pages/club/detail/clubSlide/modalContent/UniversitySelect.tsx
  src/pages/club/detail/clubSlide/modalContent/VoteModal.module.css
  src/pages/club/detail/clubSlide/modalContent/VoteModal.tsx
  src/pages/club/detail/clubSlide/modalContent/constants.ts
  src/pages/club/main/Club.tsx
  src/pages/mypage/ProfilEdit.tsx
  src/pages/vote/select/Recommend.tsx
  src/types/club.ts
  src/types/poll.ts
  src/types/univ.ts
Labels: Feature, Chore

#22 [Feature/api refresh] 리프레쉬 토큰으로 토큰 재발급 후 재요청 기능 추가
  src/apis/utils.ts
  src/constants/endpoints.ts
  src/types/auth.ts
Labels: Feature

#24 [Feature/api-club-main]동아리메인페이지 API 연결 및 디자인 수정
  src/apis/club.ts
  src/apis/poll.ts
  src/apis/secureRoutes.ts
  src/apis/team.ts
  src/components/cards/TeamCard.module.css
  src/components/cards/TeamCard.tsx
  src/components/cards/VoteCard.module.css
  src/components/cards/VoteCard.tsx
  src/components/cards/VoteCards.tsx
  src/components/slide/Slide.tsx
  src/constants/endpoints.ts
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubCalendar/ClubCalendar.tsx
  src/pages/club/detail/clubInfo/ClubInfo.module.css
  src/pages/club/detail/clubInfo/ClubInfo.tsx
  src/pages/club/detail/clubInfo/ModifyClubModal.module.css
  src/pages/club/detail/clubInfo/ModifyClubModal.tsx
  src/pages/club/detail/clubSlide/PhotoSlide.tsx
  src/pages/club/detail/clubSlide/TeamSlide.tsx
  src/pages/club/detail/clubSlide/VoteSlide.tsx
  src/pages/club/detail/clubSlide/modalContent/MemberSelect.tsx
  src/pages/club/detail/clubSlide/modalContent/TeamModal.tsx
  src/pages/club/detail/clubSlide/modalContent/UniversitySelect.tsx
  src/pages/club/detail/clubSlide/modalContent/constants.ts
  src/pages/mypage/MyPage.tsx
  src/types/club.ts
  src/types/common.ts
  src/types/poll.ts
  src/types/team.ts
Labels: Design, Feature

#27 [Feature/api team] 팀관련 API작업 및 Auth관련 버그 수정
  package-lock.json
  package.json
  src/App.tsx
  src/apis/secureRoutes.ts
  src/apis/team.ts
  src/apis/timetable.ts
  src/apis/utils.ts
  src/components/cards/TimeTableCards.module.css
  src/components/cards/TimeTableCards.tsx
  src/components/scheduler/TimeScheduler.tsx
  src/components/scheduler/constants.ts
  src/constants/endpoints.ts
  src/pages/auth/signUp/SignUpForm.tsx
  src/pages/team/Team.tsx
  src/pages/team/TeamLayout.tsx
  src/pages/team/constants.ts
  src/pages/team/detail/CreateTimeTable.module.css
  src/pages/team/detail/CreateTimeTable.tsx
  src/pages/team/detail/TeamDetail.module.css
  src/pages/team/detail/TeamDetail.tsx
  src/pages/team/detail/TeamDetailProvider.tsx
  src/pages/team/detail/constants.ts
  src/pages/team/detail/modals/KakaoShare.module.css
  src/pages/team/detail/modals/KakaoShare.tsx
  src/pages/team/detail/modals/LoadSchedules.module.css
  src/pages/team/detail/modals/LoadSchedules.tsx
  src/pages/team/detail/modals/MyTimeTables.module.css
  src/pages/team/detail/modals/MyTimeTables.tsx
  src/pages/team/detail/quickFilter/QuickFilter.module.css
  src/pages/team/detail/quickFilter/QuickFilter.tsx
  src/pages/team/detail/scheduleBoard/ScheduleBoard.module.css
  src/pages/team/detail/scheduleBoard/ScheduleBoard.tsx
  src/pages/team/detail/teamMembers/TeamMembers.module.css
  src/pages/team/detail/teamMembers/TeamMembers.tsx
  src/pages/team/teamStore.ts
  src/pages/team/useTeamController.ts
  src/types/team.ts
  src/types/timeTable.ts
  src/variables.css
Labels: bug, Feature, Chore

#25 [Feature/vote] 유튜브 임베드 코드 수정 및 서버와 타입 일치 설정
  src/constants/endpoints.ts
  src/pages/mypage/ProfilEdit.tsx
  src/pages/vote/data/dummySong.ts
  src/pages/vote/embed.ts
  src/pages/vote/select/Recommend.tsx
  src/pages/vote/select/Vote.tsx
  src/pages/vote/select/VoteButton.tsx
  src/pages/vote/select/VoteSongCard.tsx
  src/types/vote.ts
Labels: Design, Feature

#28 [Feature/api-vote] 곡 투표 API 연결 / 모달 컴포넌트 수정
  src/apis/poll.ts
  src/apis/secureRoutes.ts
  src/apis/vote.ts
  src/components/cards/VoteCard.tsx
  src/components/field/Field.module.css
  src/components/input/Input.module.css
  src/components/modal/Modal.tsx
  src/constants/endpoints.ts
  src/pages/club/detail/ClubDetail.tsx
  src/pages/club/detail/clubSlide/PhotoSlide.module.css
  src/pages/club/detail/clubSlide/TeamSlide.module.css
  src/pages/club/detail/clubSlide/VoteSlide.module.css
  src/pages/club/detail/clubSlide/VoteSlide.tsx
  src/pages/club/detail/clubSlide/modalContent/TeamModal.module.css
  src/pages/club/detail/clubSlide/modalContent/TeamModal.tsx
  src/pages/club/detail/clubSlide/modalContent/VoteModal.module.css
  src/pages/club/detail/clubSlide/modalContent/VoteModal.tsx
  src/pages/vote/data/dummySong.ts
  src/pages/vote/result/VoteResult.tsx
  src/pages/vote/select/Recommend.tsx
  src/pages/vote/select/Vote.tsx
  src/pages/vote/select/VoteButton.tsx
  src/pages/vote/select/VoteSongCard.tsx
  src/stores/voteStore.ts
  src/types/poll.ts
  src/types/vote.ts
Labels: Design, Feature

#30 [Feature/api home] 메인페이지 API 연결 및 슬라이더 설정
  src/apis/club.ts
  src/apis/promotion.ts
  src/apis/secureRoutes.ts
  src/apis/team.ts
  src/components/slide/MainSlide.module.css
  src/components/slide/MainSlide.tsx
  src/constants/endpoints.ts
  src/pages/home/BandSlide.module.css
  src/pages/home/BandSlide.tsx
  src/pages/home/Home.tsx
  src/pages/home/MyBandSlide.module.css
  src/pages/home/MyBandSlide.tsx
  src/pages/home/PromotionSlide.module.css
  src/pages/home/PromotionSlide.tsx
  src/pages/mypage/MyPage.tsx
  src/types/club.ts
  src/types/promotion.ts
  src/types/team.ts
Labels: Design, Feature, Chore

#32 [Feature/api-vote] 투표 로직 및 useDelete hook 수정
  src/apis/hooks.ts
  src/apis/mypage.ts
  src/apis/timetable.ts
  src/apis/vote.ts
  src/pages/timeSchedule/detail/TimeScheduleDetail.tsx
  src/pages/vote/select/Vote.tsx
  src/pages/vote/select/VoteButton.tsx
  src/pages/vote/select/VoteSongCard.module.css
  src/pages/vote/select/VoteSongCard.tsx
  src/types/vote.ts
Labels: Design, Feature, Chore

#34 [Feature/time table] 기획 의도를 잘못 이해해 발생한 이슈 해결
  src/App.tsx
  src/apis/secureRoutes.ts
  src/apis/timetable.ts
  src/components/cards/TeamCard.tsx
  src/components/scheduler/SelectableArea.tsx
  src/components/scheduler/TimeBoard.tsx
  src/components/scheduler/TimeLine.tsx
  src/components/scheduler/TimeScheduler.tsx
  src/constants/endpoints.ts
  src/pages/club/detail/clubSlide/modalContent/TeamModal.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/team/TeamLayout.tsx
  src/pages/team/detail/CreateTimeTable.tsx
  src/pages/team/detail/TeamDetail.tsx
  src/pages/team/detail/TeamDetailProvider.tsx
  src/pages/team/detail/constants.ts
  src/pages/team/detail/modals/LoadSchedules.module.css
  src/pages/team/detail/modals/LoadSchedules.tsx
  src/pages/team/detail/modals/MyTimeTables.module.css
  src/pages/team/detail/modals/MyTimeTables.tsx
  src/pages/team/detail/quickFilter/QuickFilter.tsx
  src/pages/team/detail/teamMembers/TeamMembers.tsx
  src/pages/timeSchedule/post/TimeSchedule.tsx
  src/types/timeTable.ts
  src/utils/timetable.ts
Labels: Feature

#36 [Feature/api-vote] 투표 취소
  src/apis/vote.ts
  src/pages/vote/graph/voteData.ts
  src/pages/vote/select/VoteButton.tsx
Labels: Feature
